apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS reviews (
      id SERIAL PRIMARY KEY,
      content TEXT
    );

    INSERT INTO reviews (content) VALUES
    ('Super produit !'),
    ('Très satisfait'),
    ('À améliorer');